Repository willowtreeapps/vocable-ios, pull requests merged in 2022-06, with the labels that each got.

#692 Test/690 Adding the AX identifiers for the Base Screen and Keyboard Screen
  Vocable/Common/Views/EmptyStateView.swift
  Vocable/Common/Views/GazeableAlertController/GazeableAlertViewController.swift
  Vocable/Features/Settings/EditCategories/CategoryNameEditorConfigurationProvider.swift
  Vocable/Features/Settings/EditPhrases/PhraseEditorConfigurationProvider.swift
  Vocable/Supporting Files/AXIdentifier/AccessibilityID+Shared+Alert.swift
  Vocable/Supporting Files/AXIdentifier/AccessibilityID+Shared.swift
  VocableUITests/Screens/BaseScreen.swift
  VocableUITests/Screens/KeyboardScreen.swift
Labels: Test verified

#691 #666 | Fix doublespeak bug
  Vocable/Common/CarouselGridCollectionViewController.swift
Labels: Test verified, Ready for Review

#693 #688 | Speech Services Unavailable UI Updates
  Vocable.xcodeproj/project.pbxproj
  Vocable/Extensions/UIApplication+Helpers.swift
  Vocable/Features/Voice/AudioPermissionPromptController.swift
  Vocable/Features/Voice/ListeningResponseEmptyStateViewController.swift
  Vocable/Supporting Files/en.lproj/Localizable.strings
Labels: Test verified

#698 #695 | Output Text After Speech Services Unavailable
  Vocable/Features/Root/RootViewController.swift
  Vocable/Features/Voice/ListeningResponseViewController.swift
Labels: Test verified, Ready for Review

#701 Bugfix for Listening Mode Empty View State
  Vocable/Features/Voice/ListeningResponseViewController.swift
Labels: Test verified, Ready for Review

#705 Test/704 Added an automation test to hide a custom category
  VocableUITests/Screens/MainScreen.swift
  VocableUITests/Tests/CustomCategoryTests.swift
Labels: Custom Categories, automation, Ready for Review, 1.4.1

#706 Update SettingsScreen.swift
  VocableUITests/Screens/SettingsScreen.swift
Labels: automation, 1.4.1

#708 Added Custom Category App Restart Tests
  Vocable.xcodeproj/project.pbxproj
  VocableUITests/Screens/CustomCategoriesScreen.swift
  VocableUITests/Screens/SettingsScreen.swift
  VocableUITests/Tests/CustomCategoryAppRestartTests.swift
Labels: Custom Categories, automation, 1.4.1
