Repository willowtreeapps/vocable-ios, pull requests merged in 2022-03, with the labels that each got.

#473 Added identifier to category carousel cell element for automation.
  Vocable/Features/Root/CategoriesCarouselViewController.swift
Labels: automation

#467 Unlink chained UI tests: CustomCategoriesTests
  Vocable.xcodeproj/project.pbxproj
  Vocable.xcodeproj/xcshareddata/xcschemes/AdHoc.xcscheme
  Vocable/Features/Settings/EditCategories/EditCategoryDetailViewController.swift
  VocableUITests/Screens/BaseScreen.swift
  VocableUITests/Screens/CustomCategoriesScreen.swift
  VocableUITests/Screens/KeyboardScreen.swift
  VocableUITests/Screens/MainScreen.swift
  VocableUITests/Screens/SettingsScreen.swift
  VocableUITests/Tests/BaseTest.swift
  VocableUITests/Tests/CustomCategoriesBaseTest.swift
  VocableUITests/Tests/CustomCategoriesTests.swift
Labels: Custom Categories, automation, Testing...

#471 #465 Allow categories and phrases to be universally editable
  Vocable.xcodeproj/project.pbxproj
  Vocable/AppDelegate.swift
  Vocable/CoreData/ModelObjectExtensions.swift
  Vocable/CoreData/NSManagedObject+Helpers.swift
  Vocable/CoreData/Phrases.xcdatamodeld/.xccurrentversion
  Vocable/CoreData/Phrases.xcdatamodeld/Phrases v4.xcdatamodel/contents
  Vocable/Extensions/Category+Helpers.swift
  Vocable/Extensions/NSPredicate+Operators.swift
  Vocable/Extensions/PredicateBuilders.swift
  Vocable/Features/Root/CategoriesCarouselViewController.swift
  Vocable/Features/Root/CategoryDetailViewController.swift
  Vocable/Features/Root/RootEditTextViewController.swift
  Vocable/Features/Settings/EditCategories/EditCategoriesViewController.swift
  Vocable/Features/Settings/EditCategories/EditCategoryDetailViewController.swift
  Vocable/Features/Settings/EditPhrases/EditPhrasesViewController.swift
Labels: Test verified

#478 #114 Add support for resetting app data via launch argument
  Vocable.xcodeproj/project.pbxproj
  Vocable.xcodeproj/xcshareddata/xcschemes/Development.xcscheme
  Vocable/AppDelegate.swift
  Vocable/CoreData/AppResetController.swift
Labels: Test verified

#479 Fix Keyboard Screen Tests
  Vocable.xcodeproj/project.pbxproj
  VocableUITests/Screens/MainScreen.swift
  VocableUITests/Tests/BaseTest.swift
  VocableUITests/Tests/CategoryIdentifier.swift
  VocableUITests/Tests/KeyboardScreenTests.swift
Labels: Test verified

#483 [114] Reset app settings via UI
  CrowdinExport/en.xliff
  Vocable.xcodeproj/project.pbxproj
  Vocable/AppDelegate.swift
  Vocable/Common/Views/GazeableAlertController/GazeableAlertViewController.swift
  Vocable/Common/Views/WarningView.xib
  Vocable/CoreData/AppResetController.swift
  Vocable/CoreData/PersistenceMigrationController.swift
  Vocable/Extensions/UIColor+AppExtensions.swift
  Vocable/Features/Root/CategoriesCarouselViewController.swift
  Vocable/Features/Settings/SettingsViewController.swift
  Vocable/Supporting Files/Assets.xcassets/Colors/Background.colorset/Contents.json
  Vocable/Supporting Files/Assets.xcassets/Colors/BorderHighlight.colorset/Contents.json
  Vocable/Supporting Files/Assets.xcassets/Colors/CategoryBackground.colorset/Contents.json
  Vocable/Supporting Files/Assets.xcassets/Colors/Contents.json
  Vocable/Supporting Files/Assets.xcassets/Colors/DefaultCellBackground.colorset/Contents.json
  Vocable/Supporting Files/Assets.xcassets/Colors/DefaultFontColor.colorset/Contents.json
  Vocable/Supporting Files/Assets.xcassets/Colors/ErrorRed.colorset/Contents.json
  Vocable/Supporting Files/Assets.xcassets/Colors/GrayDivider.colorset/Contents.json
  Vocable/Supporting Files/Assets.xcassets/Colors/Primary.colorset/Contents.json
  Vocable/Supporting Files/Assets.xcassets/Colors/Selection.colorset/Contents.json
  Vocable/Supporting Files/Assets.xcassets/Colors/TextHighlight.colorset/Contents.json
  Vocable/Supporting Files/en.lproj/Localizable.strings
Labels: Test verified

#491 #253 | Enable and update Empty State views for Sayings & Categories
  Vocable.xcodeproj/project.pbxproj
  Vocable.xcodeproj/xcshareddata/xcschemes/Development.xcscheme
  Vocable/AppConfig.swift
  Vocable/Common/Views/EmptyStateView.swift
  Vocable/Extensions/BidirectionalCollection+.swift
  Vocable/Extensions/NSRange+.swift
  Vocable/Extensions/UIEdgeInsets+Operators.swift
  Vocable/Features/Root/CategoryDetailViewController.swift
  Vocable/Features/Settings/EditPhrases/EditPhrasesViewController.swift
Labels: Test verified

#501 Test/500 fix keyboard test
  Vocable/Common/Views/EmptyStateView.swift
  VocableUITests/Screens/MainScreen.swift
  VocableUITests/Tests/KeyboardScreenTests.swift
Labels: v1.4, automation

#503 BugFix 481 | Update empty state string
  Vocable/Supporting Files/en.lproj/Localizable.strings
Labels: v1.4, Ready for Test

#496 #476 | Custom Category Refactor
  Vocable.xcodeproj/project.pbxproj
  Vocable.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Vocable/Common/CarouselGridCollectionViewController.swift
  Vocable/Common/CarouselGridLayout.swift
  Vocable/Common/NSLayoutConstraint+Priority.swift
  Vocable/Common/PagingCarouselViewController.swift
  Vocable/Common/Views/GazeableButton.swift
  Vocable/Common/VocableListCell/VocableListCell.swift
  Vocable/Common/VocableListCell/VocableListCellAccessory.swift
  Vocable/Common/VocableListCell/VocableListCellAction.swift
  Vocable/Common/VocableListCell/VocableListCellContentView.swift
  Vocable/Common/VocableListCell/VocableListCellPrimaryButton.swift
  Vocable/Common/VocableListCell/VocableListContentConfiguration.swift
  Vocable/Features/Root/CategoriesCarouselViewController.swift
  Vocable/Features/Root/CategoryDetailViewController.swift
  Vocable/Features/Root/NumericCategoryContentViewController.swift
  Vocable/Features/Settings/EditCategories/EditCategoriesViewController.swift
  Vocable/Features/Settings/EditPhrases/EditPhrasesViewController.swift
  Vocable/Features/Voice/ListeningResponseContentViewController.swift
Labels: v1.4, Test verified

#512 Re-enable CustomCategoriesTests - Refactor to leverage reset at launch
  Vocable.xcodeproj/xcshareddata/xcschemes/Development.xcscheme
  VocableUITests/Tests/CustomCategoriesBaseTest.swift
  VocableUITests/Tests/CustomCategoriesTests.swift
Labels: automation

#520 Fixed Settings Screen Tests
  Vocable.xcodeproj/xcshareddata/xcschemes/Development.xcscheme
  Vocable/Common/Views/GazeableAlertController/GazeableAlertViewController.swift
  VocableUITests/Screens/BaseScreen.swift
  VocableUITests/Screens/MainScreen.swift
  VocableUITests/Screens/SettingsScreen.swift
  VocableUITests/Tests/CustomCategoriesTests.swift
  VocableUITests/Tests/SettingsScreenTests.swift
Labels: automation

#525 Fix failing tests on PR branch for 492
  VocableUITests/Screens/SettingsScreen.swift
  VocableUITests/Tests/CustomCategoriesTests.swift
  VocableUITests/Tests/SettingsScreenTests.swift
Labels: automation
