Repository willowtreeapps/vocable-ios, pull requests merged in 2022-04, with the labels that each got.

#527 485 | Edit Category Details screen design updates 📝 🎨
  CrowdinExport/en.xliff
  Vocable.xcodeproj/project.pbxproj
  Vocable/Common/VocableListCell/VocableListCellContentView.swift
  Vocable/Common/VocableListCell/VocableListCellPrimaryButton.swift
  Vocable/Common/VocableListCell/VocableListContentConfiguration.swift
  Vocable/Features/Settings/EditCategories/EditCategoriesCompactCollectionViewCell.xib
  Vocable/Features/Settings/EditCategories/EditCategoriesDefaultCollectionViewCell.swift
  Vocable/Features/Settings/EditCategories/EditCategoriesDefaultCollectionViewCell.xib
  Vocable/Features/Settings/EditCategories/EditCategoriesViewController.swift
  Vocable/Features/Settings/EditCategories/EditCategoryDetailTitleCollectionViewCell.swift
  Vocable/Features/Settings/EditCategories/EditCategoryDetailViewController.swift
  Vocable/Features/Settings/EditCategories/EditCategoryDetailsHeaderCollectionViewCell.xib
  Vocable/Features/Settings/EditCategories/EditCategoryRemoveCollectionViewCell.swift
  Vocable/Features/Settings/EditCategories/EditCategoryRemoveCollectionViewCell.xib
  Vocable/Features/Settings/EditCategories/EditCategoryToggleCollectionViewCell.swift
  Vocable/Features/Settings/EditCategories/EditCategoryToggleCollectionViewCell.xib
  Vocable/Features/Settings/SettingsViewController.swift
  Vocable/Supporting Files/en.lproj/Localizable.strings
  VocableUITests/Screens/CustomCategoriesScreen.swift
  VocableUITests/Screens/SettingsScreen.swift
Labels: Test verified

#536 #531 | Fixing Disabled Color State
  Vocable/Common/Views/GazeableButton.swift
  Vocable/Common/VocableListCell/VocableListContentConfiguration.swift
  Vocable/Features/Settings/EditCategories/EditCategoryDetailViewController.swift
  Vocable/Features/Settings/EditPhrases/EditPhrasesViewController.swift
Labels: Test verified

#545 #522 | Updating speech icon for keyboard
  Vocable/Supporting Files/Assets.xcassets/Speak.imageset/Contents.json
  Vocable/Supporting Files/Assets.xcassets/Speak.imageset/speak.pdf
  Vocable/Supporting Files/Assets.xcassets/Speak.imageset/speak_1x.png
  Vocable/Supporting Files/Assets.xcassets/Speak.imageset/speak_2x.png
  Vocable/Supporting Files/Assets.xcassets/Speak.imageset/speak_3x.png
Labels: Test verified

#534 #494 | Gazeable Alert styling update 🖌️
  CrowdinExport/en.xliff
  Vocable/Common/Views/GazeableAlertController/GazeableAlertPresentationController.swift
  Vocable/Common/Views/GazeableAlertController/GazeableAlertViewController.swift
  Vocable/Common/Views/TextEditorNavigationButton.swift
  Vocable/Extensions/UIColor+AppExtensions.swift
  Vocable/Features/Root/CategoryDetailViewController.swift
  Vocable/Features/Settings/EditCategories/CategoryNameEditorConfigurationProvider.swift
  Vocable/Features/Settings/EditCategories/EditCategoryDetailViewController.swift
  Vocable/Features/Settings/EditPhrases/EditPhrasesViewController.swift
  Vocable/Supporting Files/Assets.xcassets/AlertBackground.colorset/Contents.json
  Vocable/Supporting Files/Assets.xcassets/Colors/AlertBackground.colorset/Contents.json
  Vocable/Supporting Files/en.lproj/Localizable.strings
  VocableUITests/Screens/SettingsScreen.swift
Labels: v1.4, Test verified

#549 [Automation] Fix MainScreenTests Suite
  Vocable.xcodeproj/xcshareddata/xcschemes/Development.xcscheme
  VocableUITests/Screens/MainScreen.swift
  VocableUITests/Tests/CategoryIdentifier.swift
  VocableUITests/Tests/MainScreenTests.swift
Labels: v1.4, automation, Test verified

#547 #493 | Toast styling update 🍞
  Vocable/Common/ToastContainerViewController.swift
  Vocable/Common/Views/ToastView.swift
  Vocable/Common/Views/ToastView.xib
Labels: Test verified

#551 [Automation] Add/Fix Custom Category Tests Suite
  Vocable.xcodeproj/project.pbxproj
  Vocable.xcodeproj/xcshareddata/xcschemes/Development.xcscheme
  Vocable/Common/VocableNavigationBar.swift
  VocableUITests/Screens/CustomCategoriesScreen.swift
  VocableUITests/Screens/MainScreen.swift
  VocableUITests/Screens/SettingsScreen.swift
  VocableUITests/Tests/CustomCategoryBaseTest.swift
  VocableUITests/Tests/CustomCategoryTests.swift
  VocableUITests/Tests/CustomPhraseBaseTest.swift
  VocableUITests/Tests/CustomPhraseTests.swift
  VocableUITests/Tests/MainScreenTests.swift
  VocableUITests/Tests/SettingsScreenTests.swift
Labels: v1.4, Custom Categories, automation

#550 #490 | Fixing Audio in Silent Mode 🔈
  Vocable/Features/Voice/SpeechRecognitionController.swift
Labels: Test verified

#552 #487 | Fixing Animation Bug Switching Between Categories 🐛
  Vocable/Features/Root/CategoriesCarouselViewController.swift
  Vocable/Features/Root/CategoryDetailViewController.swift
Labels: Test verified

#560 Fixed Settings Screen Tests
  Vocable.xcodeproj/xcshareddata/xcschemes/Development.xcscheme
  VocableUITests/Tests/SettingsScreenTests.swift
Labels: automation

#558 #553 | Fixing Volume Issue During Listening Mode 🎛️
  Vocable/Features/Voice/AudioEngineController.swift
Labels: Test verified

#557 #477 | Fixing category selection after deletion
  Vocable/Extensions/UICollectionView+Helpers.swift
Labels: Test verified

#574 [488] Add head tracking support footer text to settings ui
  Vocable/Common/Views/EmptyStateView.swift
  Vocable/Features/Settings/ListeningMode/SettingsFooterTextSupplementaryView.xib
  Vocable/Features/Settings/SelectionMode/SelectionModeViewController.swift
  Vocable/Supporting Files/en.lproj/Localizable.strings
Labels: Settings, Test verified

#564 Pagination UI Tests: Fix and Refactor
  Vocable.xcodeproj/project.pbxproj
  Vocable/Features/Settings/EditCategories/EditCategoriesViewController.swift
  VocableUITests/Screens/BaseScreen.swift
  VocableUITests/Screens/CustomCategoriesScreen.swift
  VocableUITests/Screens/KeyboardScreen.swift
  VocableUITests/Screens/MainScreen.swift
  VocableUITests/Screens/SettingsScreen.swift
  VocableUITests/Tests/BaseTest.swift
  VocableUITests/Tests/CategoryPhrasesPaginationTests.swift
  VocableUITests/Tests/CustomCategoryBaseTest.swift
  VocableUITests/Tests/CustomCategoryTests.swift
  VocableUITests/Tests/CustomPhraseBaseTest.swift
  VocableUITests/Tests/CustomPhraseTests.swift
  VocableUITests/Tests/KeyboardScreenTests.swift
  VocableUITests/Tests/MainScreenPaginationTests.swift
  VocableUITests/Tests/MainScreenTests.swift
  VocableUITests/Tests/SettingsScreenTests.swift
  VocableUITests/VocableTestAsserts.swift
  VocableUITests/XCUIElement.swift
Labels: automation

#568 [567] Phrase selection repetition bug fix
  Vocable/Common/AddPhraseCollectionViewCell.swift
  Vocable/Common/CarouselCollectionViewDataSourceProxy.swift
  Vocable/Common/CarouselGridCollectionViewController.swift
  Vocable/Common/CarouselGridLayout.swift
  Vocable/Common/PresetItemCollectionViewCell.swift
  Vocable/Common/Views/BorderedView.swift
  Vocable/Common/Views/VocableCollectionViewCell.swift
  Vocable/Features/Keyboard/KeyboardKeyCollectionViewCell.swift
  Vocable/Features/Keyboard/KeyboardViewController.swift
  Vocable/Features/Keyboard/SuggestionCollectionViewCell.swift
  Vocable/Features/Root/CategoriesCarouselViewController.swift
  Vocable/Features/Root/CategoryDetailViewController.swift
  Vocable/Features/Settings/EditPhrases/EditPhrasesCollectionViewCell.swift
  Vocable/Features/Settings/SelectionMode/Views/SettingsCollectionViewCell.swift
Labels: Test verified

#584 [575] Fix Settings layout margins
  Vocable/Features/Settings/EditPhrases/EditPhrasesViewController.swift
  Vocable/Features/Settings/ListeningMode/ListeningModeViewController.swift
  Vocable/Features/Settings/SettingsViewController.swift
  Vocable/Features/Settings/TimingSensitivity/TimingSensitivityViewController.swift
Labels: Test verified

#593 Fixed Pagination Tests
  VocableUITests/Tests/CategoryPhrasesPaginationTests.swift
  VocableUITests/Tests/CustomPhraseBaseTest.swift
  VocableUITests/Tests/MainScreenPaginationTests.swift
Labels: v1.4, automation, Test verified

#591 Adding Feature Flag for Listening Mode
  Vocable.xcodeproj/project.pbxproj
  Vocable/AppConfig.swift
  Vocable/AppDelegate.swift
  Vocable/Common/AppStorage+Init.swift
  Vocable/Common/LaunchArguments.swift
  Vocable/Common/PublishedDefault.swift
  Vocable/Features/Root/CategoriesCarouselViewController.swift
  Vocable/Features/Settings/EditCategories/EditCategoriesViewController.swift
  Vocable/Features/Settings/ListeningMode/ListeningModeViewController.swift
  Vocable/Features/Settings/SettingsViewController.swift
  Vocable/Features/Voice/ListenModeDebugView.swift
  Vocable/Features/Voice/SpeechRecognitionController.swift
  VocableUITests/Common/LaunchArguments+StringArray.swift
  VocableUITests/Tests/BaseTest.swift
Labels: Test verified

#595 [Automation] #570 | Add Preset Phrase Tests
  Vocable.xcodeproj/project.pbxproj
  Vocable/Features/Root/CategoryDetailViewController.swift
  Vocable/Features/Settings/EditPhrases/EditPhrasesViewController.swift
  VocableUITests/Screens/BaseScreen.swift
  VocableUITests/Screens/CustomCategoriesScreen.swift
  VocableUITests/Screens/MainScreen.swift
  VocableUITests/Tests/PresetPhraseTests.swift
Labels: v1.4, automation, Test verified

#601 Removing Reset App Settings As Debug Feature
  Vocable/Features/Settings/SettingsViewController.swift
Labels: Test verified, Ready for Review

#603 [556] Update Listening Mode localized strings
  Vocable.xcodeproj/project.pbxproj
  Vocable/Extensions/Category+Helpers.swift
  Vocable/Extensions/String+Localization.swift
  Vocable/Features/Settings/ListeningMode/ListeningModeViewController.swift
  Vocable/Features/Settings/SettingsViewController.swift
  Vocable/Features/Voice/ListeningResponseEmptyStateViewController.swift
  Vocable/Supporting Files/en.lproj/Localizable.strings
Labels: v1.4

#608 [602] Consolidate sources of truth for listening mode category visibilty
  Vocable.xcodeproj/project.pbxproj
  Vocable.xcodeproj/xcshareddata/xcschemes/Development.xcscheme
  Vocable/AppConfig/AppConfig.swift
  Vocable/AppConfig/ListeningModeConfig.swift
  Vocable/AppDelegate.swift
  Vocable/Extensions/Category+Helpers.swift
  Vocable/Features/Root/CategoriesCarouselViewController.swift
  Vocable/Features/Settings/EditCategories/EditCategoriesViewController.swift
  Vocable/Features/Settings/EditCategories/EditCategoryDetailViewController.swift
  Vocable/Features/Settings/ListeningMode/ListeningModeViewController.swift
  Vocable/Features/Settings/SettingsViewController.swift
  Vocable/Features/Voice/SpeechRecognitionController.swift
Labels: v1.4, Test verified

#614 [605] Make GazeableButton respect UIControl.isEnabled
  Vocable/Common/Views/GazeableButton.swift
  Vocable/Features/Settings/EditCategories/EditCategoryDetailViewController.swift
Labels: Test verified

#615 [607] Fix main screen phrases not updating when edited in settings
  Vocable/Common/CarouselCollectionViewDataSourceProxy.swift
  Vocable/Features/Root/CategoriesCarouselViewController.swift
  Vocable/Features/Root/CategoryDetailViewController.swift
  Vocable/Features/Settings/EditCategories/EditCategoriesViewController.swift
Labels: Test verified

#617 [616] Fix retain cycle crash in Category Details VC
  Vocable/Features/Root/CategoryDetailViewController.swift
  Vocable/Features/Settings/SelectionMode/SelectionModeViewController.swift
  Vocable/Features/Settings/SettingsViewController.swift
  Vocable/Features/Settings/TimingSensitivity/TimingSensitivityViewController.swift
Labels: Testing...

#619 Disabled CategoryPhrasesPaginationTests::testCanNavigatePages
  Vocable.xcodeproj/xcshareddata/xcschemes/Development.xcscheme
Labels: v1.4, automation

#621 New Crowdin updates
  CrowdinImports/da.xliff
  CrowdinImports/es.xliff
  CrowdinImports/it.xliff
  CrowdinImports/zh-Hans.xliff
  Vocable/Supporting Files/da.lproj/Localizable.strings
  Vocable/Supporting Files/es.lproj/Localizable.strings
  Vocable/Supporting Files/it.lproj/Localizable.strings
  Vocable/Supporting Files/zh-Hans.lproj/Localizable.strings
Labels: v1.4
